[package]
name = "storage-provider"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[lints.rust]
unsafe_code = "deny"
unsafe_op_in_unsafe_fn = "deny"
unused_must_use = "deny"

[lints.clippy]
all = "deny"
undocumented_unsafe_blocks = "deny"
unwrap_used = "deny"
expect_used = "deny"

[dependencies]
libloading.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
